### ISSUE TITLE
Modular configuration of menu entries

### ISSUE THREAD

**Issue by tomodachi94** [Phoenix-ComputerCraft/pxboot#2]
Hey,

I want to be able to add a file in `/boot` that will allow me to add an item to the menu, without needing to modify the `/boot/config.lua` file. How would I do that?

**Comment by walksanatora** [comment]
so like how GRUB has grub.d and it just concats those to form the grub.cfg
if i understand this right

**Comment by tomodachi94** [comment]
Yep, pretty much.

**Comment by MCJack123** [comment]
This is now possible using a line `include "config.lua.d/*"` in your main config file.

**Comment by tomodachi94** [comment]
Yay!

It should now be possible *in theory* to package various OSes through Unicornpkg and add a bootloader entry with this feature!
